export const sample_foods: any[] = [
  {
    id: "1",
    name: "Alfredo Chicken Pizza",
    desc: "An alfredo sauce base covered with chicken breast, spinach, garlic, and a mozzarella and parmesan blend",
    price: 15,
    imageUrl: "assets/alfredo-chicken-pizza.jpg",
    tags: ["Pizza", "Meat"],
  },
  {
    id: "2",
    name: "Cheese Pizza",
    desc: "Our in-house red sauce covered with a mozzarella, parmesan, provolone, and asiago blend",
    price: 5,
    imageUrl: "assets/cheese-pizza.jpg",
    tags: ["Pizza", "Vegetarian"],
  },
  {
    id: "3",
    name: "Founder's Favorite Pizza",
    desc: "Our in-house red sauce covered with pork sausage, mushrooms, and mozzarella",
    price: 10,
    imageUrl: "assets/founder-favorite-pizza.jpg",
    tags: ["Pizza", "Meat", "Popular"],
  },
  {
    id: "4",
    name: "Green Dream Pizza",
    desc: "A pesto sauce base covered with spinach, zucchini, artichoke, and a mozzarella and parmesan blend",
    price: 12,
    imageUrl: "assets/green-dream-pizza.jpg",
    tags: ["Pizza", "Vegetarian"],
  },
  {
    id: "5",
    name: "Margherita Pizza",
    desc: "Our in-house red sauce covered with tomatoes, basil, extra virgin olive oil, and mozzarella",
    price: 8,
    imageUrl: "assets/margherita-pizza.jpg",
    tags: ["Pizza", "Vegetarian", "Popular"],
  },
  {
    id: "6",
    name: "Meat Lover's Pizza",
    desc: "Our in-house red sauce covered with pork sausage, bacon, pepperoni, and a mozzarella and parmesan blend",
    price: 15,
    imageUrl: "assets/meat-lover-pizza.jpg",
    tags: ["Pizza", "Meat"],
  },
  {
    id: "7",
    name: "Pepperoni Pizza",
    desc: "Our in-house red sauce covered with pepperoni, and a mozzarella, parmesan, provolone, and asiago blend",
    price: 8,
    imageUrl: "assets/pepperoni-pizza.jpg",
    tags: ["Pizza", "Meat"],
  },
  {
    id: "8",
    name: "Vegetarian Pizza",
    desc: "Our in-house red sauce covered with mushrooms, black olives, bell peppers, onions, mushrooms, and a mozzarella and parmesan blend",
    price: 10,
    imageUrl: "assets/vegetarian-pizza.jpg",
    tags: ["Pizza", "Vegetarian"],
  },
  {
    id: "9",
    name: "Breadsticks",
    desc: "Three crispy breadsticks baked on-site",
    price: 6,
    imageUrl: "assets/breadsticks.jpg",
    tags: ["Side", "Vegetarian"],
  },
  {
    id: "10",
    name: "Caprese Salad",
    desc: "A classic salad made with tomatoes, basil, mozzarella, and balsamic viniagrette",
    price: 12,
    imageUrl: "assets/caprese-salad.jpeg",
    tags: ["Side", "Vegetarian", "Popular"],
  },
  {
    id: "11",
    name: "Caesar Salad",
    desc: "A classic salad made with romaine lettuce, croutons, parmesan, and caesar dressing",
    price: 7,
    imageUrl: "assets/caesar-salad.jpg",
    tags: ["Side", "Meat"],
  },
  {
    id: "12",
    name: "Garlic Bread",
    desc: "A half baguette covered in asiago, butter, and garlic",
    price: 5,
    imageUrl: "assets/garlic-bread.jpg",
    tags: ["Side", "Vegetarian"],
  },
  {
    id: "13",
    name: "Garden Salad",
    desc: "A classic salad made with romaine lettuce, tomatoes, black olives, red onions, croutons, and ranch dressing",
    price: 9,
    imageUrl: "assets/garden-salad.jpg",
    tags: ["Side", "Vegetarian"],
  },
  {
    id: "14",
    name: "Mozzarella Sticks",
    desc: "Five deep fried mozzarella sticks with a side of marinara sauce",
    price: 10,
    imageUrl: "assets/mozzarella-sticks.jpg",
    tags: ["Side", "Vegetarian", "Popular"],
  },
  {
    id: "15",
    name: "Almond Tart",
    desc: "Three delicious almond tarts covered in powdered sugar and apples",
    price: 6,
    imageUrl: "assets/almond-tart.jpg",
    tags: ["Dessert", "Vegetarian"],
  },
  {
    id: "16",
    name: "Chocolate Biscotti",
    desc: "Three delicious chocolate biscottis covered with a dark chocolate drizzle",
    price: 4,
    imageUrl: "assets/chocolate-biscotti.jpg",
    tags: ["Dessert", "Vegetarian"],
  },
  {
    id: "17",
    name: "Raspberry Bomboloni",
    desc: "Four delicious italian doughnuts with a raspberry filling",
    price: 8,
    imageUrl: "assets/raspberry-bomboloni.jpg",
    tags: ["Dessert", "Vegetarian"],
  },
  {
    id: "18",
    name: "Tiramisu",
    desc: "An Italian classic large enough to share with three people",
    price: 10,
    imageUrl: "assets/tiramisu.jpg",
    tags: ["Dessert", "Vegetarian", "Popular"],
  },
  {
    id: "19",
    name: "Coke",
    desc: "2 liter coca-cola bottle",
    price: 5,
    imageUrl: "assets/coke.jpg",
    tags: ["Drink", "Vegetarian", "Popular"],
  },
  {
    id: "20",
    name: "Diet Coke",
    desc: "2 liter diet coca-cola bottle",
    price: 5,
    imageUrl: "assets/diet-coke.jpg",
    tags: ["Drink", "Vegetarian"],
  },
  {
    id: "21",
    name: "Dr. Pepper",
    desc: "2 liter dr. pepper bottle",
    price: 5,
    imageUrl: "assets/dr-pepper.jpg",
    tags: ["Drink", "Vegetarian"],
  },
  {
    id: "22",
    name: "Sprite",
    desc: "2 liter sprite bottle",
    price: 5,
    imageUrl: "assets/sprite.jpg",
    tags: ["Drink", "Vegetarian"],
  },
];
